[package]
name = "wgadmin-srv"
version = "0.1.0"
authors = ["Clément L. <quadrifoglio.clement@pm.me>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-service = "1.0"
serde = "1.0"
serde_json = "1.0"

[dependencies.rwg]
git = "https://github.com/quadrifoglio/rwg.git"
